### ISSUE TITLE
Trimmed logo w/ Firefox

### ISSUE THREAD

**Issue by Manaus** [symphonycms/www-issues#1]
Hi,  
I see a trimming of the logo in the discussion page when using Firefox. 
I found the cause might be a line-height value in `#nameplate a` selector. Setting the value to `1.6` fixes the problem in FF, and won't break the page in Chrome either.

**Comment by nitriques** [comment]
Thanks Manaus.

**Comment by nitriques** [comment]
This has been fixed! Thanks again.
