### ISSUE TITLE
getsymphony.com crashes if wrong password or new account creation is attempted

### ISSUE THREAD

**Issue by andrewminton** [symphonycms/www-issues#2]
Looks like something is wrong with the events side of things me thinks. If you try to login with the wrong password or as @nitriques mentioned on gitter.im ; try to crreate a new account.. the whole page becomes unresponsive and the only we to resolve the error is to close the tab or browser and try again.

**Comment by nitriques** [comment]
Thanks Andrew.

**Comment by nitriques** [comment]
This is fixed!
