### ISSUE TITLE
Dedicated repo for "symphonyextensions.com"

### ISSUE THREAD

**Issue by twiro** [symphonycms/www-issues#3]
This new issue tracker repo for getsymphony.com reminded me of [my request](https://github.com/symphonycms/symphony-2/issues/2469#issuecomment-128973071) for introducing a dedicated github-repo for [symphonyextensions.com](http://symphonyextensions.com/).

That repo wouldn't need to actually host the code of symphonyextensions.com _(though possibly helpful)_ but could be used for tracking website issues, managing extension-related tasks and promoting knowledge and best practices regarding extension development.
### Purpose of a dedicated "symphonyextensions.com" repo
1. **Report and discuss general issues** on symphonyextensions.com.
2. **Report and discuss abandoned extensions** (organize transfer of ownership, mark obsolete extensions as deprecated, set links to recommended/supported alternatives).
3. **Promote and discuss extensions standards** (like [Extension Metadata Schema](http://symphonyextensions.com/schemas/extension/1.0/), best practices for readme-files or coding guidelines).
4. **Promote and discuss resources** that might be of interest for extensions development (including the rather hidden [migration guides](https://github.com/symphonycms/symphony-2/wiki) in the symphony wiki)
5. **Report and discuss general extensions ideas/requests**
6. **...**

The separate tasks should be listed/documented in the repo's readme so that it's easy to understand what the repo is about. I'd be happy to help with that but would prefer if a native english speaker with more knowledge of symphony's extension-eco-system could jump in here.
### One issue tracker for all Symphony Network Websites?

One might also think about using a combined issue-tracker-repo for both **getsymphony.com** and **symphonyextensions.com** _(and maybe other network websites too)_, but as most of the tasks described above are extension-specific and extend the scope of simply reporting issues I suppose  a dedicated repo that offers a clean, focused and well-documented environment for the dasks described above would be the better and more helpful solution.
### How to name the repo?

I think simply naming the repo _"symphonyextensions.com"_ would be ok, but if one thinks about that repo as a general place for managing extension related tasks (beyond the context of the extensions website) _"Symphony Extension Network"_ or simply _"Symphony Extensions"_ might even make more sense.

---

@nitriques - what do you think about it? Worth a try? _(And big thanks for already fixing some of the recent issues on symphonyextensions.com)_

@brendo, @michael-e - would like to hear your opinion too.

**Comment by nitriques** [comment]
> And big thanks for already fixing some of the recent issues on symphonyextensions.com

Thanks! I'd rather have just one and label the issue accordingly. Hence the name of the repo ;)

Your purpose list is right tho ;)

**Comment by michael-e** [comment]
Great proposal, @twiro!

Honestly I think that it should a seperate issue tracker, thus a separate repo (without code, just an issue tracker). Call it `symphony-extensions` and we are ready to go and discuss things like the following:

symphonyextensions.com is a great collection, but it's a big list of broken stuff, too. There are so many extensions which don't work as advertised, or are no longer maintained. We pretend that the community (symphonists) is a good place for these, but it is not. I am sure that the reputation of Symphony CMS has suffered a lot because of broken extensions. :-(

**Comment by nitriques** [comment]
Could we call it symext-issues ?

> I am sure that the reputation of Symphony CMS has suffered a lot because of broken extensions. :-(

It did.

>  We pretend that the community (symphonists) is a good place for these, but it is not.

Why so ?

**Comment by michael-e** [comment]
Because it has turned out that the community doesn't have the power to fix all that stuff.

**Comment by nitriques** [comment]
Most of the time, it's only a matter of updating the xml file since most of them are still working.

I try to to my best on that, but fixing bugs is often more urgent

**Comment by michael-e** [comment]
> but fixing bugs is often more urgent

Sure!

> Most of the time, it's only a matter of updating the xml file since most of them are still working.

Well, yes, for some of them this is true.

Just in case there would be some cleanup going on, I could provide a list of "personally verified" extensions — extensions which I use in production without issues. (Only a few of them have open pull requests to achieve this.)

**Comment by nitriques** [comment]
Yes please! Opening an issue is better than nothing!

**Comment by twiro** [comment]
> Could we call it symext-issues ?

If we're going to create a separate repo I'd really vote for a name that doesn't imply a focus on "issues" only. And I'd prefer something more "human readable". Have some ideas but will have to post them later...

[ von unterwegs ]

**Comment by nitriques** [comment]
>  I'd really vote for a name that doesn't imply a focus on "issues" 

Well, that the only reason the repo have to exist!

**Comment by twiro** [comment]
> _symphonyextensions.com is a great collection, but it's a big list of broken stuff, too. There are so many extensions which don't work as advertised, or are no longer maintained. We pretend that the community (symphonists) is a good place for these, but it is not. I am sure that the reputation of Symphony CMS has suffered a lot because of broken extensions. :-(_

That's the point. I really enjoy working with Symphony and regarding the core and some "wellknown & trusted" extensions the development-experience never has been better for me. But regarding extensions in general I have to admit that I greatly benefit from my longtime experience with Symphony and the fact that I know **where to look** and **what to consider** regarding which extension, which fork and which branch I might actually use for a project. There's a lot of working stuff out there, but it's not always in the master branch, let alone the _official_ main repo of the extension.

Newer Symphony adopters don't have this experience and must rely on the official resources to judge which extensions might suit their needs. And while symphonyextensions.com in general is an awesome tool for that it definitively faces the problems michael mentioned above.

And it would be cool to have a central place (the repo we're talking about) that tries to get extension developers (and users) involved in helping to create a cleaner, more reliable and better documented extension-eco-system.

> _Most of the time, it's only a matter of updating the xml file since most of them are still working._

Exactly. And that's an area where guys like me - who make heavy use of extensions but aren't experienced or great extension developers - could probably help out more. By reporting stuff like "I noticed that extension XY listed on symphonyextensions is outdated or promoted in an irritiating/false manner but I found that branch ABC works just fine with Symphony X.Y.Z - anything we could do about that?".

And as this might concern lots of somehow abandoned extensions I think a central place (the repo we're talking about) that gathers people who are actively interested in maintaining a solid and sustainable extension-eco-system would be a more efficient and pragmatic solution when spreading issues all over unmaintained extension-repos, rarely read forum-threads, short-lived gitter-chats or even the main symphony repository.

> _Just in case there would be some cleanup going on, I could provide a list of "personally verified" extensions — extensions which I use in production without issues. (Only a few of them have open pull requests to achieve this.)_

One more great usecase for the repo we're talking about :) This could be promoted as another "best practice" in the readme and motivate developers to share their personal "extension whitelists" from time to time.

It's tasks like this (among others) that make me think focusing solely on the term "**issues**" in the repo name would unnecessarily narrow down the scope of what that repo would be understood as (and could be used for).

> _Well, that the only reason the repo have to exist!_

Technically yes, we would use "github _**issues**_" to post things and discuss stuff, but regarding the actual content tasks like the one mentioned by michael as well as most of the stuff I posted in my initial list don't really fit under that term. And that's the reason why I proposed a separate repo - while this one is clearly promoted as a "website issue tracker" I feel that the extension-eco-system could need something more... rereading my post I actually like the description I wrote above:

_**"a central place (repo) that tries to get extension developers (and users) involved in helping to create a cleaner, more reliable and better documented extension-eco-system".**_

And I'm all for a human readable name because that not only would make it easier to understand what the repo is about but would also help in getting not-so-tech-savvy-users involved by having a name that can be told, promoted and spread even outside of the strictly technical focussed github-cosmos.

But this is getting long... will think about it some more and post my name-proposals later ;)

**Comment by twiro** [comment]
> _We pretend that the community (symphonists) is a good place for these, but it is not._

By the way... wouldn't it make sense to create that "Symphony Extensions"-repo in the symphonists-account? If we'd aim to establish it as the central place for the community to discuss, organize and help with the symphony-extension-eco-system this would be the perfect fit in my eyes. Could also be used to define what "**Symphonists**" actually is/means. And to strengthen their powers ;)

> _Thanks! I'd rather have just one and label the issue accordingly. Hence the name of the repo ;)_

Another thought... would it make sense to separate concerns in the following way:
- Repo "**symphonycms/www-issues**":  Issue tracker for all symphony related websites. The main focus lies on _technical_ bugs.
- Repo "**symphonists/symphony-extension-network**": The "central place" for discussing, organizing and optimizing the symphony-extension-eco-system. As described in this thread.

**Comment by nitriques** [comment]
> more reliable and better documented extension-eco-system.

For that matter, we need to leverage the current php eco-system, i.e. composer.

> works just fine with Symphony X.Y.Z - anything we could do about that?

Best thing would be to open an issue on github for that project. It's easier to follow and I can close tickets directly via git. There even a link on symphony ext to create a new ticket.

I know who I can blindly trust on that and I do not mind editing the file myself and push a new version :p

That being said I agree with your latest proposal.

**Comment by twiro** [comment]
A little off-topic, but I'll post it here, as the discussion around this kind of topic would fit perfectly in the scope of a dedicated "symphony extensions"-repo :) So it's a good example of what could better be discussed/managed/organized there:

---

I contacted Twisted Interactive earlier this year and offered them to take over ownership of their unmaintained **"[reflected upload field](https://github.com/twiro/reflecteduploadfield)"** and **"[slider](https://github.com/twiro/slider)"**-extensions. Thanks to @joostkamphuis we successfully transfered the repos today and after some code clean up and updating _(working on this!)_ I'll have to [repost](https://github.com/twiro/reflecteduploadfield/issues/9) "reflected upload field" on symphonyextensions.com and request a [change of ownership](http://symphonyextensions.com/extensions/slider/) for the "slider"-extension.

The first task shouldn't be a problem, but for the second one a "symphony extensions"-repo that would maybe offer me a "how-to-transfer-ownership-on-symphonyextensions.com" guide as well as the possibility to file a new issue to request the change if I can't do it myself would be a pretty good start!

---

Regarding cleaning up the extension-eco-system I also asked Twisted if they would be ok with transfering their two most popular extensions to the symphonists-account. **[Author Roles](http://symphonyextensions.com/extensions/author_roles/)** and **[Import CSV](http://symphonyextensions.com/extensions/importcsv/)** are the perfect examples for outdated listings on symphonyextensions.com while [lots of fixes](https://github.com/TwistedInteractive/importcsv/network) and more actively [maintained](https://github.com/symphonists/author_roles/network) forks exist on github.

Having them on the symphonists-account would at least offer the option to consolidate some of the fixes in a new release and offer the "best possible" version on symphonyextensions.com.

@nitriques I asked Joost to add you the twisted team temporary so that you could manage the transfering of the repos... I hope you don't mind! Maybe he already sent you an invitation...

**Comment by nitriques** [comment]
> a "how-to-transfer-ownership-on-symphonyextensions.com" guide as well as the possibility to file a new issue to request the change if I can't do it myself would be a pretty good start!

Good point!

> Having them on the symphonists-account would at least offer the option to consolidate 

Perfect!

As for the update on the extension site, it needs to be done manually. I can do it quickly when notified, I do not mind ;)

**Comment by nitriques** [comment]
[There you go](https://github.com/symphonists/symphony-extensions-network)

**Comment by twiro** [comment]
> That being said I agree with your latest proposal.

Cool!
You mean that one, right?

---
- Repo **"symphonycms/www-issues"**: Issue tracker for all symphony related websites. The main focus lies on _technical_ bugs.
- Repo **"symphonists/symphony-extension-network"**: The "central place" for discussing, organizing and optimizing the symphony-extension-eco-system. As described in this thread.

---

@michael-e - what do you think? Ok with that?

And is there a name we could agree upon? "**symphony-extension-network**" would be my current favourite (as beeing the most descriptive option), but "**symphony-extensions**" sounds just fine (and flexible enough) too...

**Comment by twiro** [comment]
> _There you go_

You're acting faster than I can write ;)
But... cool, thank you very much!
I hope everyone's ok with the name...

**Comment by nitriques** [comment]
:rocket:

**Comment by nitriques** [comment]
I've also change the setting of the cron job on the extension site.. it's now every 5 min ;) (so one extension gets check every 5 mins) So it takes 28 hours to complete a run. (instead of 7 days)

**Comment by twiro** [comment]
So I'd really like to help defining what this repo is about as good as i can - most possibly by contributing to the readme _(though I always need my time for writing in english)_... should I fork and send PRs or would it make sense to become a direct member/contributor?

And where do you both see the scope of this repo?
Like described in my initial post... minus the reporting of technicla bugs on the website?
Other things we should include in the readme?

I think we need to start small, but in the long run it would be really great to build a set of "Best Practices", "Howtos" and "FAQs" regarding extension development/maintenance/documentation etc.

**Comment by nitriques** [comment]
> would it make sense to become a direct member/contributor?

If you want that, I am ok with it!

> And where do you both see the scope of this repo?

Anything really that does not have its dedicated repo

>  build a set of "Best Practices", "Howtos" and "FAQs" regarding extension development/maintenance/documentation etc.

That's cool!

**Comment by michael-e** [comment]
@twiro: Thanks for your commitment and your ideas! Cool.

@nitriques: thanks for making the extension site faster!

**Comment by nitriques** [comment]
:)

**Comment by twiro** [comment]
> >  would it make sense to become a direct member/contributor?
> 
> If you want that, I am ok with it!

Not sure if it makes sense in the long run (I'd have to leave all of the technical stuff to you) but I'd be fine with gathering some more git/github-experience while helping to shape the readme and documentation for that repo... so if you don't mind just add me and I'll give my best to contribute something useful!

By the way: [just posted the first issue](https://github.com/symphonists/symphony-extensions-network/issues/1), so you can start introducing a labeling system ;)

**Comment by nitriques** [comment]
> so you can start introducing a labeling system ;)

I think you can now do it :+1:

**Comment by twiro** [comment]
So one of the first things we should probably do is set up a first small version of a readme that defines scope & purpose of the repo so that people understand what it's about.

After that is included we could post & promote the repo wherever it makes sense (symphony forum, extensions site, gitter) and engange extension developers (and users) to watch it, use it and contribute.

@nitriques - should I start writing something... by extending the list in my initial post? Or do you want to? Should we collect ideas about scope & purpose here or start a new issue in the new repo?

I'm off for today (and most of the weekend), but will maybe find some time for writing...

**Comment by twiro** [comment]
_> I think you can now do it_

Cool - thank you! Can I create new labels (like "sympohnyextensions.com")

**Comment by nitriques** [comment]
>  should I start writing something... by extending the list in my initial post? 

Yes please do ! Thanks!

**Comment by nitriques** [comment]
I'll close this for now. Please continue discussion in the new repo :)

**Comment by twiro** [comment]
> > should I start writing something... by extending the list in my initial post?
> 
> Yes please do ! Thanks!

Ok... might take a few days, but i'll give my best to set something useful up as soon as possible!

**Comment by nitriques** [comment]
> Ok... might take a few days, but i'll give my best to set something useful up as soon as possible!

No stress!

**Comment by nitriques** [comment]
Github API seems to allow us to update a extension every minutes! All extensions are now processed in 5.5 hours !
